### ISSUE TITLE
Learn programming

### ISSUE THREAD

**Issue by Aditbar** [Aditbar/Elementary-My-Dear-Watson#2]
For information check
https://github.com/Aditbar/Elementary-My-Dear-Watson

Please mention the link to your working file
example:
Haskell - https://github.com/Aditbar/Elementary-My-Dear-Watson/blob/master/Haskell/Template.hs
Pandas - ....
Numpy - ....
etc

don't forget to always commit your work, whether or not it has finished. So, we can see and review the progress.

**Comment by nugiasmara** [comment]
Haskell - https://github.com/nugiasmara/hello-world/blob/master/Template.hs
